server:
  port: 8080

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  dbname: cross_border_shop

redis:
  host: localhost
  port: 6379
  password: ""

jwt:
  web_secret: maimamihoue
  web_expire: 24h
  plugin_secret: shahoude
  plugin_expire: 720h  # 30天，考虑到插件离线使用

payment:
  order_expire: 5m

wechat:
  app_id: wxf8b4f85f3a794e77
  app_secret: 5c96fac3c8774d0d279b407f9861ae22

captcha:
  expiration: 5m
  length: 6