server:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  dbname: cross_border_shop

redis:
  host: localhost
  port: 6379
  password: ""

jwt:
  web_secret: your-web-secret-key
  web_expire: 24h
  plugin_secret: your-plugin-secret-key
  plugin_expire: 720h  # 30天，考虑到插件离线使用

payment:
  order_expire: 5m